name: Push to Balena
on: [push]
jobs:
  build:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
    - name: Git Add Remote
      run: git remote add balena ${{ secrets.BALENA_REPOSITORY }}
    - name: Git Push
      run: git push balena master
