name: Docker Image Build 🐋

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, production ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Checkout submodules 🛎️
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up QEMU 🔧
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Build the Docker Image 🐋
      run: docker build . -t simplesignage
    - name: Save the Docker Image 💾
      run: docker save simplesignage > SimpleSignage.tar
    - name: Upload Docker Image ✈
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ./SimpleSignage.tar
    image-push:
      if: github.ref == 'refs/heads/production'
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Push to GitHub Packages
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: JeffResc/SimpleSignage/simplesignage
            tag_with_ref: true
